import { sha256 } from '@noble/hashes/sha2.js'

/**
 * RFC 8785 canonicalization, and the digest a signature is taken over.
 *
 * ## Written from the specification, deliberately
 *
 * The CMS has its own implementation of this. **This one does not share a line with it.** The
 * conformance corpus is generated by the signer, and a verifier built on the signer's own code would
 * agree with it no matter what either of them did — the run would look like evidence and be none.
 * The only thing the two are permitted to share is the signature primitive.
 *
 * ## What a cross-language implementer gets wrong
 *
 * Two things, per the specification, and both are here:
 *
 * - **Keys sort by UTF-16 code unit, not by locale.** A locale-aware sort puts `ä` beside `a`; JCS
 *   puts it after `z`. JavaScript's default `Array.prototype.sort` on strings compares UTF-16 code
 *   units, which is the rule — but only because the default is used. `localeCompare` would be wrong.
 * - **Omitted is not null.** `{}` and `{"minimum":null}` are different documents with different
 *   digests, so an absent key must stay absent and a null must stay null.
 */

type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue }

class CanonicalizationError extends Error {
  constructor (message: string) {
    super(message)
    this.name = 'CanonicalizationError'
  }
}

/**
 * A number, in the form ECMAScript produces.
 *
 * `JSON.stringify` already emits exactly what RFC 8785 asks for: shortest round-trip, `1e+30` for
 * large magnitudes, no trailing `.0` on an integral double. What it does not do is refuse `NaN` and
 * the infinities — it renders them `null`, which would attest to a value nobody supplied.
 *
 * Negative zero is normalized to zero here rather than left to `JSON.stringify`, which renders `-0`
 * as `0` already; stating it means the rule survives a change of serializer.
 */
const canonicalNumber = (value: number): string => {
  if (!Number.isFinite(value)) {
    throw new CanonicalizationError(`${String(value)} has no JSON representation`)
  }
  return JSON.stringify(value === 0 ? 0 : value)
}

/**
 * A string, escaped as JSON requires and no further.
 *
 * Non-ASCII stays literal: `€` is one character, not `€`. `JSON.stringify` escapes only what
 * the grammar requires, which is the rule.
 */
const canonicalString = (value: string): string => JSON.stringify(value)

/** Sorted by UTF-16 code unit. `<` on strings is that comparison, and it is the whole rule. */
const sortedKeys = (value: Record<string, JsonValue>): string[] =>
  Object.keys(value).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))

const canonicalize = (value: JsonValue): string => {
  if (value === null) return 'null'
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return canonicalNumber(value)
  if (typeof value === 'string') return canonicalString(value)

  // Array order carries meaning and is never sorted.
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`

  if (typeof value !== 'object') {
    throw new CanonicalizationError(`${typeof value} has no JSON representation`)
  }

  const object = value as Record<string, JsonValue>
  const members = sortedKeys(object).map((key) => {
    const member = object[key]
    // An `undefined` member is not an absent one: the caller wrote the key. Dropping it silently is
    // how a verifier ends up disagreeing with the signer about what the document was.
    if (member === undefined) {
      throw new CanonicalizationError(`member '${key}' is undefined, which JSON cannot represent`)
    }
    return `${canonicalString(key)}:${canonicalize(member)}`
  })
  return `{${members.join(',')}}`
}

/** The 32 bytes a signature is taken over. Not the canonical bytes themselves — their SHA-256. */
const digest = (value: JsonValue): Uint8Array =>
  sha256(new TextEncoder().encode(canonicalize(value)))

export { canonicalize, digest, CanonicalizationError }
export type { JsonValue }
