import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { canonicalize, digest } from './canonical.js'

/**
 * Agreement with the signer, checked against the corpus rather than against the signer's code.
 *
 * `conformance/vectors.json` records, for each vector, the payload, its canonical string and its
 * digest — produced by the CMS. This file re-derives both from **this** implementation and compares.
 * Nothing is imported from the CMS, which is the only reason the comparison means anything.
 *
 * The specification is explicit about how to read a disagreement: it *"localises an ambiguity in
 * this document, which is the artefact under evaluation — not the implementations."* So a failure
 * here is a finding about the specification first, and about this code second.
 *
 * The envelope vectors and their verdicts are step 19's business; this is the canonicalization half,
 * which is what the verifier already has.
 */

interface CanonicalVector {
  name: string
  why: string
  payload: unknown
  canonical: string
  digest: string
}

const hex = (bytes: Uint8Array): string =>
  [...bytes].map(byte => byte.toString(16).padStart(2, '0')).join('')

/**
 * Where the corpus is, if it is anywhere.
 *
 * Named by an environment variable rather than by a path. The corpus is generated by
 * `packages/core/scripts/generate-conformance.ts` and published alongside the specification, which
 * is **not this repository** — so a hard-coded path would work on exactly one machine and would ship
 * inside a package that other people install.
 *
 * Absent, these are skipped. Step 19 makes the corpus a first-class input rather than an optional
 * one; until then this runs wherever it is pointed at something.
 */
const CORPUS = process.env.GENOACMS_CONFORMANCE_CORPUS ?? ''

const corpus = CORPUS !== '' && existsSync(CORPUS)
  ? JSON.parse(readFileSync(CORPUS, 'utf8')) as { canonicalization?: CanonicalVector[] }
  : undefined

const vectors = corpus?.canonicalization ?? []

describe.skipIf(vectors.length === 0)('the conformance corpus', () => {
  it('has vectors to check', () => {
    expect(vectors.length).toBeGreaterThan(0)
  })

  it.each(vectors.map(vector => [vector.name, vector] as const))(
    'canonicalizes %s as the signer did',
    (_name, vector) => {
      expect(canonicalize(vector.payload as never)).toBe(vector.canonical)
    }
  )

  it.each(vectors.map(vector => [vector.name, vector] as const))(
    'digests %s as the signer did',
    (_name, vector) => {
      expect(hex(digest(vector.payload as never))).toBe(vector.digest)
    }
  )
})
