import { matrixOperations, rolesUnderTest, BUCKET, COLLECTION } from '../evidence/permissionMatrix'

/**
 * Emits the E6 permission matrix as a Markdown table.
 *
 * Purely computational — it reads no configuration, touches no bucket and no secret store, so it is
 * safe to run to see what it does.
 *
 * It prints the **expectations**, which are asserted against the real services by
 * `permissionMatrix.test.ts`. The table is therefore only evidence when that suite passes; printing
 * it does not verify anything by itself, and the two share one declaration so they cannot drift.
 */

const roleNames = Object.keys(rolesUnderTest)

const describeGrants = (roleName: string): string => {
  const { grants } = rolesUnderTest[roleName]
  if (grants.length === 0) return '*none*'
  return grants
    .map(grant => {
      const permission = grant.permission === '*' ? '\\*' : `\`${grant.permission}\``
      const resource = typeof grant.resource === 'string'
        ? (grant.resource === '*' ? 'any' : grant.resource)
        : `${grant.resource.scope} \`${grant.resource.id}\``
      return `${permission} on ${resource}`
    })
    .join('<br>')
}

const cell = (roleName: string, operation: string): string =>
  rolesUnderTest[roleName].allowed.includes(operation) ? '✔' : '·'

function renderRoleTable (): string {
  const rows = roleNames.map(name => `| **${name}** | ${describeGrants(name)} |`)
  return ['| Role | Grants |', '| :--- | :--- |', ...rows].join('\n')
}

function renderMatrix (): string {
  const header = `| Operation | ${roleNames.join(' | ')} |`
  const divider = `| :--- | ${roleNames.map(() => ':---:').join(' | ')} |`
  const rows = matrixOperations.map(operation =>
    `| \`${operation}\` | ${roleNames.map(role => cell(role, operation)).join(' | ')} |`
  )
  return [header, divider, ...rows].join('\n')
}

function summary (): string {
  const cells = roleNames.length * matrixOperations.length
  const allows = roleNames.reduce(
    (total, role) => total + matrixOperations.filter(op => rolesUnderTest[role].allowed.includes(op)).length,
    0
  )
  return [
    `- **${roleNames.length} roles × ${matrixOperations.length} service functions = ${cells} assertions.**`,
    `- ${allows} expected allows, ${cells - allows} expected denials.`,
    `- Resource-scoped grants name bucket \`${BUCKET}\` and collection \`${COLLECTION}\`.`
  ].join('\n')
}

const output = [
  '# E6 — Authorization Correctness: Permission Matrix',
  '',
  'Generated by `scripts/generate-permission-matrix.ts`. Every cell is asserted against the real',
  'service-layer function by `permissionMatrix.test.ts`; a function missing its permission check',
  'appears as an unexpected allow, which is how the fail-closed property is made',
  'detectable by construction.',
  '',
  summary(),
  '',
  '## Roles under test',
  '',
  renderRoleTable(),
  '',
  '## Matrix',
  '',
  '`✔` permitted · `·` denied',
  '',
  renderMatrix(),
  '',
  '## Field-level masking',
  '',
  'The two assertions §4.4.6 also calls for are covered, in `permissionMatrix.test.ts` rather than in',
  'this table — they are about the *contents* of a document rather than about whether an operation is',
  'permitted, so they do not fit a role-by-function grid:',
  '',
  '- **New-field default deny** — a grant naming fields covers exactly those, so a field added to the',
  '  schema afterwards is stripped on read and ignored on write.',
  '- **Write-merge integrity** — a principal who cannot write a field cannot erase it by omitting it;',
  '  the stored value is preserved.',
  '',
  'Both are driven through the real gated service, and both are mutation-tested: removing the read',
  'projection, or replacing the write merge with an overwrite, fails two assertions each.',
  ''
].join('\n')

console.log(output)
