import { expect, type Page, type Locator } from '@playwright/test'

/**
 * The content the consumer demos render.
 *
 * ## Why this is a Playwright scenario rather than a script
 *
 * Everything the demos read has to be **published by the CMS the way an author publishes it** —
 * signed by the live subordinate key, pinned by a real page tree, written to the instance's bucket.
 * A script that wrote the objects directly would be a second producer of the very documents the SDK
 * exists to verify, and the first thing it would prove is that the corpus was generated by whoever
 * also checks it. Driving the interface is what keeps the demo honest evidence.
 *
 * ## The prefix is the contract
 *
 * Everything created here is named `demo…`, and `demoCleanup.spec.ts` removes exactly that. The
 * end-to-end suites use `e2e…` and sweep their own, so the two never see each other's fixtures.
 *
 * **Pages are removed before components.** A component a published page pins cannot be deleted — the
 * CMS refuses it — so cleaning up in the other order fails on every component at once and leaves the
 * instance exactly as it was.
 *
 * ## Names are shared with the demo applications
 *
 * `PAGES` below is what the demo apps ask for by name. Renaming anything here means renaming it
 * there, which is why the list is exported rather than written out twice.
 */

const PREFIX = 'demo'

/** The components the pages are composed from, and what each accepts. */
const COMPONENTS = {
  /** A page root: nothing but a slot. */
  page: { name: `${PREFIX}Page`, attributes: [{ type: 'components', name: 'body' }] },
  /** A titled region that holds other things — what makes nesting possible. */
  section: {
    name: `${PREFIX}Section`,
    attributes: [{ type: 'string', name: 'heading' }, { type: 'components', name: 'content' }]
  },
  /** A leaf with two text values, so parameter order is observable in the output. */
  card: {
    name: `${PREFIX}Card`,
    attributes: [{ type: 'string', name: 'title' }, { type: 'text', name: 'body' }]
  },
  /** A leaf mixing types, so a renderer that stringifies everything is visible. */
  note: {
    name: `${PREFIX}Note`,
    attributes: [{ type: 'string', name: 'text' }, { type: 'number', name: 'order' }]
  }
} as const

/**
 * The pages the demos render, by name.
 *
 * Chosen to be **different shapes rather than more content**: each one exercises something a
 * renderer can get wrong on its own.
 */
const PAGES = {
  /** Depth, breadth and repetition together. The one the demos show by default. */
  home: `${PREFIX}Home`,
  /** Siblings and no nesting — the simplest tree that is not a single node. */
  flat: `${PREFIX}Flat`,
  /** A slot with nothing in it, which must render as a parent with no children. */
  empty: `${PREFIX}Empty`
} as const

/** The card in the slot for a nested node, by the component it holds. */
const nestedCard = (page: Page, component: string): Locator =>
  page.locator('.card')
    .filter({ has: page.getByRole('link', { name: 'Edit' }) })
    .filter({ hasNot: page.getByRole('button', { name: 'Add component' }) })
    .filter({ hasText: component })

/**
 * The editor for one attribute, found by the heading that names it.
 *
 * Attribute names are `<h3>` headings rather than labels — the input is not associated with the name
 * — so `getByLabel` finds nothing and a page-wide `getByRole('textbox')` would find every attribute
 * at once. The card carrying the heading is the only stable handle.
 */
const attributeCard = (page: Page, name: string): Locator =>
  page.locator('.card').filter({
    has: page.getByRole('heading', { name, exact: true })
  })

// ---------------------------------------------------------------------------------------------
// The registrar
// ---------------------------------------------------------------------------------------------

const registerComponent = async (page: Page, name: string): Promise<void> => {
  await page.goto('/components/registrar')
  await page.getByRole('button', { name: 'Register component' }).click()
  await page.getByLabel('Component name:').fill(name)
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByText(`Component: ${name}`)).toBeVisible()
}

const addAttribute = async (page: Page, type: string, name: string): Promise<void> => {
  await page.getByRole('button', { name: 'Add attribute' }).click()
  await page.getByText(type, { exact: true }).click()
  // The newest attribute is appended, so its name field is the last on the page.
  const field = page.getByLabel('Name:').last()
  await expect(field).toBeVisible()
  await field.fill(name)
}

const saveComponent = async (page: Page): Promise<void> => {
  await page.getByRole('button', { name: 'Submit' }).click()
  await expect(page.getByText(/success|saved|updated/i).first()).toBeVisible({ timeout: 20_000 })
}

/**
 * Publishes the component whose registrar page is open.
 *
 * Waits for the **badge** rather than the toast: the toast is transient, and a scenario that missed
 * it would report a failure for a publication that actually succeeded.
 */
const publishComponent = async (page: Page): Promise<void> => {
  await page.getByRole('button', { name: 'Publish' }).click()
  const dialog = page.getByRole('dialog', { name: 'Publish the component' })
  await dialog.getByRole('textbox').last().fill('published for the consumer demos')
  await dialog.getByRole('button', { name: /publish/i }).click()
  await expect(page.getByText('Published', { exact: true })).toBeVisible({ timeout: 30_000 })
}

/** Registers a component, describes it, saves it and releases it. */
const createComponent = async (
  page: Page,
  component: { name: string, attributes: ReadonlyArray<{ type: string, name: string }> }
): Promise<void> => {
  await registerComponent(page, component.name)
  for (const attribute of component.attributes) {
    await addAttribute(page, attribute.type, attribute.name)
  }
  await saveComponent(page)
  await publishComponent(page)
}

// ---------------------------------------------------------------------------------------------
// The page editor
// ---------------------------------------------------------------------------------------------

const createPage = async (page: Page, name: string, root: string): Promise<void> => {
  await page.goto('/components/pages')
  await page.getByRole('button', { name: 'Create page' }).click()
  await page.getByLabel('Name:').fill(name)
  await page.getByLabel('Component:').selectOption({ label: root })
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('heading', { name })).toBeVisible()
}

const openPage = async (page: Page, name: string): Promise<void> => {
  await page.goto(`/components/pages/${name}`)
  await expect(page.getByRole('heading', { name })).toBeVisible()
}

/**
 * Adds a component to the slot currently on screen.
 *
 * The picker's buttons carry an icon before their label, so their accessible name has a leading
 * space and an exact match never matches. The form around each is the stable handle.
 */
const nest = async (page: Page, component: string): Promise<void> => {
  const before = await nestedCard(page, component).count()
  await page.getByRole('button', { name: 'Add component' }).click()
  await page.locator('form').filter({ hasText: component }).getByRole('button').click()
  await expect(nestedCard(page, component)).toHaveCount(before + 1)
}

/**
 * Opens the nth node of a component for editing, descending one level into the tree.
 *
 * Waited for by the **URL changing**, not by a control appearing. Every control in the top panel —
 * Save, Build, Undo — belongs to the page rather than to the node and is on screen the whole time,
 * so waiting for one of those would return immediately and read the previous node's attributes.
 */
const openNested = async (page: Page, component: string, index = 0): Promise<void> => {
  const before = page.url()
  await nestedCard(page, component).nth(index).getByRole('link', { name: 'Edit' }).click()
  await page.waitForFunction(previous => globalThis.location.href !== previous, before)
}

/** Fills a text-shaped attribute — `string` is an input, `text` a textarea. */
const fill = async (page: Page, attribute: string, value: string): Promise<void> => {
  const card = attributeCard(page, attribute)
  const field = card.locator('input[type="text"], textarea, input[type="number"]').first()
  await expect(field).toBeVisible()
  await field.fill(value)
}

/**
 * Saves the node on screen.
 *
 * `Save` rather than `Submit`: the page editor's control carries `aria-label="Save"`, and `Submit`
 * is the *registrar's*. The two editors are different screens and the same word for both was simply
 * wrong.
 */
const saveNode = async (page: Page): Promise<void> => {
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText(/saved/i).first()).toBeVisible({ timeout: 20_000 })
}

/**
 * Builds the page's readable tree — the document a consumer actually fetches.
 *
 * Everything before this is a draft the CMS holds. This is the step that signs a tree, pins the
 * publication each node was composed against, and writes it where the SDK looks.
 */
const buildPage = async (page: Page): Promise<void> => {
  await page.getByRole('button', { name: 'Build' }).click()
  await expect(page.getByText(/saved|built|success/i).first()).toBeVisible({ timeout: 30_000 })
}

export {
  PREFIX, COMPONENTS, PAGES,
  createComponent, registerComponent, publishComponent, saveComponent, addAttribute,
  createPage, openPage, nest, openNested, fill, saveNode, buildPage, nestedCard
}
